# Generated by Django 2.1.7 on 2019-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
