# Generated by Django 2.1.7 on 2019-04-19 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190419_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_dates',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance'),
        ),
    ]
